/* Automatically generated by configure */
#ifndef COMPONENTS_CONFIG_H
#define COMPONENTS_CONFIG_H


int _papi_hwi_max_presets[] = {
   PAPI_MAX_PRESET_EVENTS,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0
};

hwi_presets_t *_papi_hwi_comp_presets[] = {
   _papi_hwi_presets,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL
};

extern papi_vector_t _perf_event_vector;
extern papi_vector_t _perf_event_uncore_vector;
extern papi_vector_t _appio_vector;
extern papi_vector_t _coretemp_vector;
extern papi_vector_t _infiniband_vector;
extern papi_vector_t _io_vector;
extern papi_vector_t _lmsensors_vector;
extern papi_vector_t _net_vector;
extern papi_vector_t _powercap_ppc_vector;
extern papi_vector_t _sensors_ppc_vector;
extern papi_vector_t _sde_vector;
extern papi_vector_t _rapl_vector;
extern papi_vector_t _sysdetect_vector;

struct papi_vectors *_papi_hwd[] = {
   &_perf_event_vector,
   &_perf_event_uncore_vector,
   &_appio_vector,
   &_coretemp_vector,
   &_infiniband_vector,
   &_io_vector,
   &_lmsensors_vector,
   &_net_vector,
   &_powercap_ppc_vector,
   &_sensors_ppc_vector,
   &_sde_vector,
   &_rapl_vector,
   &_sysdetect_vector,
   NULL
};

#endif
