PACKAGE_TARNAME = papi
prefix = /home/users/tburgess/treece_cypapi_fork/cyPAPI/papi-7.2.0/src/papi_build_ppc64le_gcc
exec_prefix = ${prefix}
datarootdir = ${prefix}/share
datadir = ${datarootdir}/${PACKAGE_TARNAME}
DATADIR = $(DESTDIR)$(datadir)
INCLUDE = -I. -I${prefix}/include
CC	= gcc
F77	= gfortran
CC_R	= $(CC) -pthread
CFLAGS	=   -DPAPI_NUM_COMP=13 -O1
ENABLE_FORTRAN = yes
